### ISSUE TITLE
[dmpy] don't use 'ob_*' for every struct

### ISSUE THREAD

**Issue by bmr-cymru** [bmr-cymru/dmpy#7]
People will start laughing.

**Comment by nirs** [comment]
I think people will cry :-), but this is is certainly nice cleanup.

**Comment by bmr-cymru** [comment]
👍 :-)

**Comment by bmr-cymru** [comment]
Took a wrong assumption from a tutorial - it's just one of those annoying, easy but fiddly bits of cleanup that's really easy to keep putting off...

**Comment by bmr-cymru** [comment]
While I was reviewing this I noticed some garbage (a vim .swo file) that had been included in an earlier commit - I've removed it with a rebase and updated the tree, so existing clones of the repo will need to be rebased.

**Comment by nirs** [comment]
Why you need unique member names for structs? How does it assist in debugging?

**Comment by bmr-cymru** [comment]
Yes - lots of things have a sequence member, but if you see for e.g. `dr_sequence` you can assume right away it's a `DmStatsRegion` object.

**Comment by bmr-cymru** [comment]
It's also helpful if you ever need to refactor or rename any of these members - one of the things that made this change fiddly was the fact that there were numerous `ob_stats`, `ob_sequence` etc. members - so you can't simply use a global `s/ob_sequence/dr_sequence/g` - every instance has to be carefully checked to see what type of struct is being referenced (sometimes it's very obvious, other times you have to really read the code). When the struct member names are always unique you can safely use a global replace.
